### ISSUE TITLE
Quick Latex for Mobile 

### ISSUE THREAD

**Issue by vaughnmonkey** [joeyuping/quick_latex_obsidian#28]
I love your plugin on my desktop it makes writing latex a million times easier. I really wish it would work on mobile and don't know if theres some reason that it can't or if its just an option that you could enable.

**Comment by joeyuping** [comment]
hi!

thank you for the suggestion!
I have tried enabling the mobile option, however it seems that the way this plugin is written does not work in the mobile environment. I may need some serious try and error to see where the issue may be.

**Comment by Aplietexe** [comment]
As the documentation for [the `isDesktopOnly` key in `manifest.json`](https://github.com/obsidianmd/obsidian-api) seems to suggest, plugins don't work on mobile because they use some NodeJS or Electron API. Just throwing [browserify](https://browserify.org) at the problem might solve the issue by virtue of providing browser alternatives to Node APIs, which should also work on the Obsidian mobile app.
