### ISSUE TITLE
Custom shorthands using symbols fail if typed too quickly

### ISSUE THREAD

**Issue by pokir** [joeyuping/quick_latex_obsidian#69]
Bug description:
- Make a custom shorthand with a symbol such as `*:\cdot ;`
- Type `*` followed by a space quickly in a latex block
- The `*` doesn't turn into `\cdot `

This doesn't seem to happen with letters.

Quick Latex for Obsidian version 2.4.0

**Comment by joeyuping** [comment]
Hi @pokir !

Thank you for bringing this up. After testing, the reason is because the custom shorthand function is triggered by "space". When using a symbol as shorthand, specifically symbols that requires pressing the "shift" key, then keying "too fast" could result in user pressing "space" before the "shift" has been released, which cause the plugin to register a "shift-space" input and so do not trigger the custom shorthand function.  Please kindly see if this is the case on your side as well. If that is true, I see if I can allow the function to fire also in the case of shift space.

**Comment by pokir** [comment]
@joeyuping

That is the case on my side as well.

**Comment by joeyuping** [comment]
Hi! @pokir 

Really sorry for the very late update!
I have added that shift-space would trigger custom shorthand as well. Hope this works for your case too :)
