### ISSUE TITLE
Using brackets with pre-selected text removes the expression

### ISSUE THREAD

**Issue by DaSh-More** [joeyuping/quick_latex_obsidian#73]
https://user-images.githubusercontent.com/52647986/197335823-3a1921d1-6b3d-4a89-a438-03664504c4c3.mp4

**Comment by joeyuping** [comment]
hi! @DaSh-More 

on my windows version of obsidian v0.16.4, the enclosing of selected text with brackets is already an inbuilt function of obsidian. whether the plugin is active or not the function is still present... sorry I wasnt able to replicate your issue ... might it be due to the version of obsidian you are using?

**Comment by DaSh-More** [comment]
Maybe I have Obsidian 1.0.0 and didn't seem to have this problem before the update

**Comment by DaSh-More** [comment]
https://user-images.githubusercontent.com/52647986/197466543-cc0314a3-c314-4962-bac4-1c030a86c683.mp4

An interesting point is that if you select text from right to left, everything works fine, but if from left to right, the expression is deleted. Apparently it has something to do with which position is considered the initial and which is the final

**Comment by joeyuping** [comment]
Hi! @DaSh-More 

Thank you so much! This did help to pin-point the bug!
I have resolved this issue in v2.5.1.  Please kindly update the plugin and see it works well on yourside.
