### ISSUE TITLE
Plugin not working after consecutive inline formula

### ISSUE THREAD

**Issue by JeffeyChou** [joeyuping/quick_latex_obsidian#94]
Dear author, I really appreciate your plugin that did save lots of time in my work flow.

However, I found a issue that the plugin doesn't working after two consecutive inline formulas. A GIF that shows this problem is showed as follows.
![issue](https://github.com/joeyuping/quick_latex_obsidian/assets/90391082/57593445-6442-4e71-9cb9-8921bf389999)

**Comment by joeyuping** [comment]
Hi @JeffeyChou !

Thank you so much for bringing this up !!

This may have been because :

$ equation1 $$ equation2 $

the double dollar signs in between may have been recognized as the start of a full width equation. 

it should work if there is a space in between: 
$ equation1 $ $ equation2 $

is that the case?  might this work around be ok?

**Comment by JeffeyChou** [comment]
Yeah, I appreciate your work!

Though it seems like a small issue, I hope it may provide some useful information for you and other who encounter this problem!
